<?xml version="1.0" encoding="utf-8"?><Database Name="TechSupport" Class="Assignment5LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=cissql.matrix.txstate.edu\cis3325fall18;Initial Catalog=TechSupport;Integrated Security=True" SettingsObjectName="Assignment5UserInterface.Properties.Settings" SettingsPropertyName="TechSupportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Incident" Member="Incidents" ThisKey="CustomerID" OtherKey="CustomerID" Type="Incident" />
      <Association Name="State_Customer" Member="State1" ThisKey="State" OtherKey="StateCode" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Incidents" Member="Incidents">
    <Type Name="Incident">
      <Column Name="IncidentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TechID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOpened" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateClosed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Incident" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="StateCode" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstZipCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastZipCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="State_Customer" Member="Customers" ThisKey="StateCode" OtherKey="State" Type="Customer" />
    </Type>
  </Table>
</Database>